matrix:
  include:
    # - language: python
    #   python: 
    #     - 3.4
    #   before_install:
    #     - cd backend/
    #   install: 
    #     - pip install -r requirements.txt
    #   script:
    #     - python manage.py test

    - language: node_js
      node_js:
        - node
      before_install:
        - cd web-client
      install:
        - npm install
      script:
        - npm run lint && npm run type-check && npm run test

notifications:
  email: false