# Generated by Django 3.1.5 on 2021-01-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driving", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NM", "Not Matched"),
                            ("R", "Referred"),
                            ("MNC", "Matched not Confirmed"),
                            ("MAC", "Matched and Confirmed"),
                            ("FU", "Follow Up"),
                            ("MI", "Match Incomplete"),
                            ("RMR", "Rematch Required"),
                        ],
                        max_length=3,
                    ),
                ),
                ("email", models.TextField()),
                ("advisor_name", models.TextField()),
                ("languages", models.TextField()),
                ("organization_referral", models.TextField()),
                ("second_match", models.TextField()),
                (
                    "community",
                    models.CharField(
                        choices=[
                            ("DT", "Downtown Toronto"),
                            ("NYE", "North York East"),
                            ("NYW", "North York West"),
                            ("MTT", "Mid Town Toronto"),
                            ("EYB", "East York/ Beaches"),
                            ("SE", "Scarborough East"),
                            ("SW", "Scarborough West"),
                            ("NE", "North Etobicoke"),
                            ("SE", "South Etobicoke"),
                            ("TW", "Toronto West"),
                        ],
                        max_length=3,
                    ),
                ),
                ("other", models.TextField()),
                ("contactless", models.BooleanField()),
                ("high_risk_contact", models.BooleanField()),
                ("up_to_thirty", models.BooleanField()),
                ("up_to_fifty", models.BooleanField()),
                ("packaging_sorting", models.BooleanField()),
                ("car_access", models.BooleanField()),
                ("van_truck_access", models.BooleanField()),
                ("one_mill_insurance", models.BooleanField()),
                ("two_mill_insurance", models.BooleanField()),
                ("G_license", models.BooleanField()),
                ("other_license_class", models.TextField()),
            ],
        ),
    ]
