# Generated by Django 3.1.7 on 2021-03-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0002_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleDriver',
        ),
    ]
