# Generated by Django 3.1.7 on 2021-03-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0003_delete_exampledriver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='G_license',
            new_name='g_license',
        ),
    ]
