name: 'PR'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify pull request.
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+\/(Sub|SUB|sub)?([0-9])+' # Regex the title should match.
          allowed_prefixes: 'feature,hotfix,release'
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|release|hotfix)\/(SUB|Sub|sub)?[1-9]([0-9])*$' # Regex the branch should match. This example enforces grouping
          ignore: master,develop # Ignore exactly matching branch names from convention
      - uses: actions/github-script@v4
        env:
          target: GITHUB_BASE_REF
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const getIssueNumber = (title)=>{
                let issueNumber = title.split('/')[1]
                if(issueNumber[0].toUpperCase() === 'S'){
                    issueNumber = issueNumber.slice(3)
                }
                return issueNumber;
            }
            const { target } = process.env;
            const prntLabelRegex = /^prnt-.*/;
            const {data: issue} = await github.issues.get({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            const issueNumber = getIssueNumber(issue.title)
            const {data: labels} = await github.issues.listLabelsOnIssue({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            const prntLabels = labels.filter(label=>prntLabelRegex.test(label.name))
            const feature = labels.find(label=>label.name==='feature');
            let error = '';
            if(feature){
                if(target !== 'develop'){
                    error = `You are attempting to merge into the wrong branch. Change the pull request so that it is set to merge to develop.`;
                }
            } else {
                
                if(prntLabels.length === 1){
                    const parentNumber = prntLabels[0].name.split('-')[1]
                    const errorMessage = `You are attempting to merge into the wrong branch. Change the pull request so that it is set to merge to feature/${parentNumber}.`;
                    if(/feature\//i.test(target)){
                        const branchNumber = getIssueNumber(target)
                        if(branchNumber !== parentNumber){
                            error = errorMessage
                        }
                    } else {
                        error = errorMessage
                    }
                    
                }
            }
            if(error){
                core.setFailed();
            }
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {data: issue} = await github.issues.get({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            const issueNumber = issue.title.split('/')[1]

            const {data: issues} = await github.issues.listForRepo({
                labels: `prnt-${issueNumber}`,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
            });
            
            if(issues.length){
                core.setFailed(`The issue you are working on has child issues that are not closed yet. Those child tickets must be closed (completed) before you can merge this ticket. Their titles are:\n- ${issues.map(issue=>`${issue.title} | ${issue.number} | ${issue.html_url}`).join('\n- ')}.`);
            }