name: 'PR'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify pull request.
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+\/([0-9])+' # Regex the title should match.
          allowed_prefixes: 'feature,hotfix,release'
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|release|hotfix)\/[1-9]([0-9])*$' # Regex the branch should match. This example enforces grouping
          ignore: master,develop # Ignore exactly matching branch names from convention
      - uses: actions/github-script@v4
        env:
          target: GITHUB_BASE_REF
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prntLabelRegex = /^prnt-.*/;
            const prntLabels = context.issue.labels.filter(label=>prntLabelRegex.test(label.name))
            if(prntLabels.length === 1){
              const branchNumber = target.split('/')[1]
              const parentNumber = prntLabels[0].name.split('-')[1]
              if(branchNumber !== parentNumber){
                core.setFailed(`You are attempt to merge into the wrong branch. Change the pull request so that it is set to merge to feature/${parentNumber}`);
              }
            }


        