name: 'PRTitle'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify pull request.
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(feature|hotfix|release)\/([0-9])+' # Regex the title should match.
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|release|hotfix)\/[1-9]([0-9])*$' # Regex the branch should match. This example enforces grouping
          ignore: master,develop # Ignore exactly matching branch names from convention
      - uses: hattan/verify-linked-issue-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: 'Build Error! No linked issue found. Please link an issue to this pull request'